CREATE TABLE TB_USERS (
	ID_USER BIGINT NOT NULL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
	SALARIO DECIMAL NOT NULL,
	PERFIL VARCHAR(100) NOT NULL,
	STATUS VARCHAR(100) NOT NULL,
	CREATE_DATETIME TIMESTAMP NOT NULL DEFAULT NOW(),
	CREATE_USER_ID BIGINT,
	UPDATE_DATETIME TIMESTAMP,
	UPDATE_USER_ID BIGINT,
	CONSTRAINT FK_CREATE_USER_ID FOREIGN KEY (CREATE_USER_ID) REFERENCES TB_USERS(ID_USER),
	CONSTRAINT FK_UPDATE_USER_ID FOREIGN KEY (UPDATE_USER_ID) REFERENCES TB_USERS(ID_USER)
);
CREATE SEQUENCE TB_USERS_SEQ;