CREATE TABLE TB_PARAMETERS (
	ID_PARAMETER BIGINT NOT NULL PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	VALOR VARCHAR(100) NOT NULL,
	STATUS VARCHAR(100) NOT NULL,
	CREATE_DATETIME TIMESTAMP NOT NULL DEFAULT NOW(),
	CREATE_USER_ID BIGINT,
	UPDATE_DATETIME TIMESTAMP,
	UPDATE_USER_ID BIGINT,
	CONSTRAINT FK_TB_PARAM_CREATE_USER_ID FOREIGN KEY (CREATE_USER_ID) REFERENCES TB_USERS(ID_USER),
	CONSTRAINT FK_TB_PARAM_UPDATE_USER_ID FOREIGN KEY (UPDATE_USER_ID) REFERENCES TB_USERS(ID_USER)
);
CREATE SEQUENCE TB_PARAMETERS_SEQ;