CREATE TABLE TB_HORAS_EXTRAS (
	ID_HORAS_EXTRAS BIGINT NOT NULL PRIMARY KEY,
	ID_USUARIO BIGINT NOT NULL,
	DATA_HORA_INICIO TIMESTAMP NOT NULL,
	DATA_HORA_FIM TIMESTAMP NOT NULL,
	DESCRICAO VARCHAR(255),
	ID_USUARIO_APROVADOR BIGINT NOT NULL,
	STATUS VARCHAR(100) NOT NULL,
	CREATE_DATETIME TIMESTAMP NOT NULL DEFAULT NOW(),
	CREATE_USER_ID BIGINT,
	UPDATE_DATETIME TIMESTAMP,
	UPDATE_USER_ID BIGINT,
	CONSTRAINT FK_TB_HORAS_EXTRAS_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USERS(ID_USER),
	CONSTRAINT FK_TB_HORAS_EXTRAS_ID_USUARIO_APROVADOR FOREIGN KEY (ID_USUARIO_APROVADOR) REFERENCES TB_USERS(ID_USER),
	CONSTRAINT FK_TB_HORAS_EXTRAS_CREATE_USER_ID FOREIGN KEY (CREATE_USER_ID) REFERENCES TB_USERS(ID_USER),
	CONSTRAINT FK_TB_HORAS_EXTRAS_UPDATE_USER_ID FOREIGN KEY (UPDATE_USER_ID) REFERENCES TB_USERS(ID_USER)
);
CREATE SEQUENCE TB_HORAS_EXTRAS_SEQ;