CREATE TABLE TB_LINKS (
	ID_LINK UUID NOT NULL PRIMARY KEY,
	ID_HORA_EXTRA BIGINT NOT NULL,
	ACAO VARCHAR(20) NOT NULL,
	STATUS VARCHAR(100) NOT NULL,
	CREATE_DATETIME TIMESTAMP NOT NULL DEFAULT NOW(),
	CREATE_USER_ID BIGINT,
	UPDATE_DATETIME TIMESTAMP,
	UPDATE_USER_ID BIGINT,
	CONSTRAINT FK_TB_LINKS_ID_HORA_EXTRA FOREIGN KEY (ID_HORA_EXTRA) REFERENCES TB_HORAS_EXTRAS(ID_HORAS_EXTRAS),
	CONSTRAINT FK_TB_LINKS_CREATE_USER_ID FOREIGN KEY (CREATE_USER_ID) REFERENCES TB_USERS(ID_USER),
	CONSTRAINT FK_TB_LINKS_UPDATE_USER_ID FOREIGN KEY (UPDATE_USER_ID) REFERENCES TB_USERS(ID_USER)
);